# yaml-language-server: $schema=../../schema/config.json
---
terminology:
  l1:
    singular: "Environment"
    plural: "Environments"
  l2:
    singular: "Segment"
    plural: "Segments"
schema_path: "../../schema/"
