# yaml-language-server: $schema=../pkg/domain/schemas/config.json
---
terminology:
  l1:
    singular: "Environment"
    plural: "Environments"
  l2:
    singular: "Segment"
    plural: "Segments"
schema_path: "pkg/domain/schemas"
